### ISSUE TITLE
Where's the "Installed" Plugin's Source Code?

### ISSUE THREAD

**Issue by d14na** [HelloZeroNet/Plugin-PeerMessage#8]
Quick question! I'm working with the PluginManager recently introduced by @HelloZeroNet. I can install and test PeerMessage just fine _(as I was able to do by cloning the source directly into `/plugins`)_. However, after __INSTALLING__ using the manager, I can't find the source code anywhere; especially NOT in `/plugins` folder where I would expect it to be _COPIED??_

I imagine `UiPluginManager` is putting the source _SOMEWHERE_. Again, the plugin works fine, and gets listed under `plugins` when requesting `serverInfo`. _(NOTE: it shows up last, NOT in alphabetical order, so being appended??)_

I've seen mention of `== "builtin"`??, but don't know what that's for.

One thing that I suspect _could be_ happening, is that `UiPluginManager` is storing a reference to the zite where the plugin code was __sourced from__ and then executes from there?? doesn't seem very secure to me, so that's a long shot.

@imachug any help/insight would much appreciated.

**Comment by purplesyringa** [comment]
`data/__plugins__/siteaddress/path/to/plugin/within/site`
